<a href="https://colab.research.google.com/github/kanankiri91/KeyLock-Defenders/blob/main/kekuatan_password_skripsi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv("/content/drive/MyDrive/data.csv", on_bad_lines='skip')

In [6]:
df.head()
df.shape

(669640, 2)

In [7]:
df["strength"].unique()

array([1, 2, 0])

In [8]:
df.describe()

strength
count  669640.000000
mean        0.990196
std         0.507948
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000

In [9]:
df.isnull().sum()

password    1
strength    0
dtype: int64

In [10]:
df=df.dropna()

In [11]:
X=df.drop("strength",axis=1).values.flatten()
y=df["strength"].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
y_train

array([1, 1, 2, ..., 1, 1, 2])

In [13]:
def tokens(string):
    """break strings into characters"""
    return [x for x in string]

In [14]:
password_clf=Pipeline([("vect",TfidfVectorizer(tokenizer=tokens)),("clf",DecisionTreeClassifier())])

In [15]:
password_clf.fit(X_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('vect',
                 TfidfVectorizer(tokenizer=<function tokens at 0x78f35adf5480>)),
                ('clf', DecisionTreeClassifier())])

In [16]:
password_clf.score(X_test,y_test)

0.9284839615315692

In [17]:
strong="AVYq1lDE4MgAZfNt"
medium="schalke04"
weak="qwerty"

In [18]:
password_clf.predict([strong,medium,weak])

array([2, 1, 0])

In [20]:
import pickle

In [21]:
with open('password_model.pkl', 'wb') as model_file:
    pickle.dump(password_clf, model_file)
print("pipeline saved")

pipeline saved
